### ISSUE TITLE
Document how to build on Windows

### ISSUE THREAD

**Issue by ayshih** [sunpy/pyflct#10]
Here is a draft:

1. Set up the build environment if not already set up (and it's important to setup up MSVC rather than MinGW)
  * Download "Build Tools for Visual Studio 2019" (https://visualstudio.microsoft.com/downloads/)
  * Install, making sure to check the option "C++ build tools" in the installer
2. Set up FFTW
  * Download ZIP file of precompiled FFTW Windows DLLs (http://www.fftw.org/install/windows.html) and extract contents to a folder
  * Open the application "Developer Command Prompt for VS2019", change to the above folder, and run the following commands to create the import libraries (`libfftw3*.lib`):
```
lib /def:libfftw3-3.def /machine:x64
lib /def:libfftw3f-3.def /machine:x64
lib /def:libfftw3l-3.def /machine:x64
```
  * Copy the `libfftw3*.dll` files to somewhere in `%PATH%` (or add the FFTW folder to `%PATH%`)
3. Modify `pyflct/setup_package.py` if not already modified so that the compilation options include the FFTW folder for `include_dirs` and `library_dirs` and the library names for `libraries`.

**Comment by ayshih** [comment]
I'll note that the precompiled DLLs on the FFTW website are apparently not as up to date as what is available through `conda-forge` (cf. #7).

**Comment by nabobalis** [comment]
In #12 I have a version of this to the docs along with some changes to enable support for anaconda FFTW.
