### ISSUE TITLE
Consider changing the license to LGPL

### ISSUE THREAD

**Issue by ayshih** [sunpy/pyflct#11]
`pyflct` is currently licensed as GPL v3, which could have implications for the license of any package that imports it (but people do disagree).  It contains Berkeley C code ([licensed as LGPL v2](http://cgem.ssl.berkeley.edu/cgi-bin/cgem/FLCT/artifact/7e9001629d1bff57)) and links to FFTW ([nominally licensed as GPL v2](http://www.fftw.org/fftw3_doc/License-and-Copyright.html)).  If FFTW is GPL, it is normally understood that `pyflct` must be GPL because it builds an extension that links to FFTW.

However, FFTW apparently offers a [non-GPL license for purchase](http://www.fftw.org/faq/section1.html#nonfree) as well.  This is the loophole that `pyfftw` uses to [assert a 3-clause BSD license](https://pyfftw.readthedocs.io/en/latest/source/license.html): if the user happens to have a non-GPL license for FFTW, then there is no GPL implication to that user's `pyfftw`.

`pyflct` may want to consider arguing that same – possibly sketchy – loophole to switch to LGPL.  ~(The Berkeley C code will prevent switching to anything more permissive.)~

**Comment by Cadair** [comment]
Yeah this shouldn't be GPLv3, it should be LGPL or even BSD. I have further thoughts on licensing in general for this which I don't have time to type out right now :rofl:

**Comment by nabobalis** [comment]
What should it be then?

**Comment by nabobalis** [comment]
In #12 I have changed it to the LGPL.
